extends: airbnb-base
rules:
  function-paren-newline: off
  no-unused-expressions: off
  no-console: off
  no-confusing-arrow: off
  no-param-reassign: off
  no-shadow: off
  consistent-return: off
  import/no-dynamic-require: off